name: Build and Release

on:
  release:
    types: [published] # Triggers when a new release is published

env:
  OUTPUT_FOLDER: './artifact'

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Create output folder
        run: mkdir -p ${{ env.OUTPUT_FOLDER }}

      - name: Package the application
        run: |
          PACKAGE_NAME="my-app-${{ github.event.release.tag_name }}.tgz"
          npm pack
          mv *.tgz ${{ env.OUTPUT_FOLDER }}/$PACKAGE_NAME

      - name: Upload artifact to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: '${{ env.OUTPUT_FOLDER }}/*.tgz'
          tag: ${{ github.event.release.tag_name }}
          name: ${{ github.event.release.name }}
          draft: false
          prerelease: ${{ github.event.release.prerelease }}
          replacesArtifacts: true
          generateReleaseNotes: true
