name: Build and Release

on:
  release:
    types: [published] # Triggers when a new release is published

env:
  OUTPUT_FOLDER: './artifact'

jobs:
  build:
    permissions: write-all
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Generate version suffix
        id: version
        run: |
          # Extract version suffix from the tag
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build the application
        env:
          TAG_NAME: ${{ env.TAG_NAME }}
          W3C_MODE_ENABLED: ${{ env.W3C_MODE_ENABLED }}
        run: npm run build

      - name: Upload packaged app using GitHub CLI
        run: |
          gh release upload "${{ github.event.release.tag_name }}" "${{ env.OUTPUT_FOLDER }}/Risk Europe ${{ env.TAG_NAME }}.w3x" --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ env.TAG_NAME }}
